export enum ConfigVariables {
  DOMAIN = 'MEDIATOR_DOMAIN',
  KEY_AGREEMENT_ECDH_PUBLIC_JWK = 'MEDIATOR_KEY_AGREEMENT_ECDH_PUBLIC_JWK',
  KEY_AGREEMENT_ECDH_PRIVATE_JWK = 'MEDIATOR_KEY_AGREEMENT_ECDH_PRIVATE_JWK',
  DATABASE_URL = 'MEDIATOR_DATABASE_URL',
}
