export enum ConfigVariables {
  DOMAIN = 'DOMAIN',
  KEY_AGREEMENT_ECDH_PUBLIC_JWK = 'KEY_AGREEMENT_ECDH_PUBLIC_JWK',
  KEY_AGREEMENT_ECDH_PRIVATE_JWK = 'KEY_AGREEMENT_ECDH_PRIVATE_JWK',
  DATABASE_URL = 'DATABASE_URL',
}
