export enum ConfigVariables {
  DOMAIN = 'MEDIATOR_DOMAIN',
  KEY_AGREEMENT_X25519_PUBLIC_JWK = 'MEDIATOR_KEY_AGREEMENT_X25519_PUBLIC_JWK',
  KEY_AGREEMENT_X25519_PRIVATE_JWK = 'MEDIATOR_KEY_AGREEMENT_X25519_PRIVATE_JWK',
  VERIFICATION_ED25519_PUBLIC_JWK = 'MEDIATOR_VERIFICATION_ED25519_PUBLIC_JWK',
  VERIFICATION_ED25519_PRIVATE_JWK = 'MEDIATOR_VERIFICATION_ED25519_PRIVATE_JWK',
  DATABASE_URL = 'MEDIATOR_DATABASE_URL',
}
