export enum ConfigVariables {
  DOMAIN = 'REGISTRY_DOMAIN',
  KEY_AGREEMENT_ECDH_PUBLIC_JWK = 'REGISTRY_KEY_AGREEMENT_ECDH_PUBLIC_JWK',
  KEY_AGREEMENT_ECDH_PRIVATE_JWK = 'REGISTRY_KEY_AGREEMENT_ECDH_PRIVATE_JWK',
  DATABASE_URL = 'REGISTRY_DATABASE_URL',
}
